### ISSUE TITLE
Invalid config in version 2022.1.0

### ISSUE THREAD

**Issue by miguelpucela** [nielsfaber/alarmo-card#23]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
I've updated to last version and HA notifies an error.

### Actual behavior

The notification:

Invalid config
The following integrations and platforms could not be set up:
irrigation_unlimited
Please check your config and logs.

And the logs gives three errors with this information:

Error adding entities for domain irrigation_unlimited with platform irrigation_unlimited
11:46:09 – (ERROR) Irrigation Unlimited (custom integration)
Logger: custom_components.irrigation_unlimited
Source: custom_components/irrigation_unlimited/entity.py:111
Integration: Irrigation Unlimited (documentation, issues)
First occurred: 11:46:09 (1 occurrences)
Last logged: 11:46:09
Error adding entities for domain irrigation_unlimited with platform irrigation_unlimited
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 747, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/irrigation_unlimited/entity.py", line 111, in async_added_to_hass
    data = IUAdjustment(zne[ATTR_ADJUSTMENT]).to_dict()
KeyError: 'adjustment'

Error during setup of component irrigation_unlimited
11:46:09 – (ERROR) Irrigation Unlimited (custom integration)
Logger: homeassistant.setup
Source: custom_components/irrigation_unlimited/entity.py:111
Integration: Irrigation Unlimited (documentation, issues)
First occurred: 11:46:09 (1 occurrences)
Last logged: 11:46:09
Error during setup of component irrigation_unlimited
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/irrigation_unlimited/__init__.py", line 251, in async_setup
    await component.async_add_entities([IUComponent(coordinator)])
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 747, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/irrigation_unlimited/entity.py", line 111, in async_added_to_hass
    data = IUAdjustment(zne[ATTR_ADJUSTMENT]).to_dict()
KeyError: 'adjustment'

Exception in <file.irrigation_unlimited_service_shim.irrigation_unlimited_list_config> line 39: data = json.loads(irrigation_unlimited.coordinator.configuration) ^ AttributeError: 'StateVal' object has no attribute 'configuration'
11:46:51 – (ERROR) Pyscript Python scripting (custom integration) - message first occurred at 11:46:49 and shows up 2 times
Logger: custom_components.pyscript.file.irrigation_unlimited_service_shim.irrigation_unlimited_list_config
Source: custom_components/pyscript/eval.py:480
Integration: Pyscript Python scripting (documentation, issues)
First occurred: 11:46:49 (2 occurrences)
Last logged: 11:46:51
Exception in <file.irrigation_unlimited_service_shim.irrigation_unlimited_list_config> line 39: data = json.loads(irrigation_unlimited.coordinator.configuration) ^ AttributeError: 'StateVal' object has no attribute 'configuration'

### Steps to Reproduce
Just updating to last version and restarting HA.

**Comment by nielsfaber** [comment]
You're posting this in the wrong place.
The error has nothing to do with scheduler.

**Comment by miguelpucela** [comment]
You're  right. Sorry.
